### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by luisaesposito** [luisaesposito/camisaslegais2#2]
- [ ] fazer login no admin leva direto para dashboard, deve levar para home.
- [ ] ao ficar no dashboard por alguns minutos e clicar em home, continuo logado mas não aparece o link para dashboard no header
- [ ] clicar em conta deve levar para uma página de form com inputs desabilitados com valores sendo a info do usuario vindos do BD.
  - ao clicar no botão editar conta, os inputs ficam habilitados para o usuario poder editar e aparece um botão que fará UPDATE
- [ ] criar página de melhores avaliados
  - deve ser igual loja, mas na ordem de avaliação
